# Generated by Django 5.1.2 on 2025-02-24 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PZWapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='povrtnabiljka',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='povrtne_biljke', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vrtnabiljka',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vrtne_biljke', to=settings.AUTH_USER_MODEL),
        ),
    ]
