# Generated by Django 5.1.2 on 2025-02-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PZWapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='povrtnabiljka',
            name='slikaBiljke_p',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vrtnabiljka',
            name='slikaBiljke_v',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('povrtne_biljke', models.ManyToManyField(blank=True, to='PZWapp.povrtnabiljka')),
                ('vrtne_biljke', models.ManyToManyField(blank=True, to='PZWapp.vrtnabiljka')),
            ],
        ),
    ]
