# Generated by Django 5.1.2 on 2025-02-28 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PZWapp', '0002_alter_povrtnabiljka_user_alter_vrtnabiljka_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='povrtnabiljka',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='povrtne_biljke', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vrtnabiljka',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vrtne_biljke', to=settings.AUTH_USER_MODEL),
        ),
    ]
