# Generated by Django 5.1.2 on 2025-02-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PZWapp', '0002_alter_povrtnabiljka_slikabiljke_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='povrtne_biljke',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='vrtne_biljke',
        ),
        migrations.AddField(
            model_name='korisnik',
            name='lozinka',
            field=models.CharField(default='12345', max_length=128),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='username',
            field=models.CharField(default='rino', max_length=50, unique=True),
        ),
    ]
