# Generated by Django 5.1.2 on 2025-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PZWapp', '0002_alter_povrtnabiljka_user_alter_vrtnabiljka_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
