# Generated by Django 5.1.2 on 2025-02-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PZWapp', '0003_alter_korisnik_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='povrtnabiljka',
            name='slikaBiljke_p',
        ),
        migrations.RemoveField(
            model_name='vrtnabiljka',
            name='slikaBiljke_v',
        ),
    ]
