# Generated by Django 5.1.2 on 2025-02-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PZWapp', '0003_alter_povrtnabiljka_user_alter_vrtnabiljka_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='povrtnabiljka',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vrtnabiljka',
            name='user',
        ),
    ]
