# Generated by Django 5.1.2 on 2025-02-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PZWapp', '0004_remove_povrtnabiljka_slikabiljke_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='povrtnabiljka',
            name='regijaBiljke_p',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='povrtnabiljka',
            name='vrijemeSazrijevanja_p',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vrtnabiljka',
            name='regijaBiljke_v',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vrtnabiljka',
            name='vrijemeSazrijevanja_v',
            field=models.CharField(max_length=50),
        ),
    ]
